[build]
  command = "pnpm run build"
  publish = "dist/"

[build.environment]
  NODE_VERSION = "24"
  PNPM_VERSION = "11"

[[plugins]]
  package = "netlify-plugin-cache"
  [plugins.inputs]
    paths = ["dist/img"]
