allowBuilds:
  esbuild: true
  sharp: true
minimumReleaseAgeExclude:
  - eslint-config-reverentgeek
  - eleventy-plugin-edgejs
  - '@11ty/eleventy@4.0.0-alpha.8'
  - '@pnpm/exe.android-arm64@12.10.0'
  - '@pnpm/exe.android-x64@12.10.0'
  - '@pnpm/exe.darwin-arm64@12.10.0'
  - '@pnpm/exe.darwin-x64@12.10.0'
  - '@pnpm/exe.freebsd-x64@12.10.0'
  - '@pnpm/exe.linux-arm64-musl@12.10.0'
  - '@pnpm/exe.linux-arm64@12.10.0'
  - '@pnpm/exe.linux-ppc64@12.10.0'
  - '@pnpm/exe.linux-riscv64@12.10.0'
  - '@pnpm/exe.linux-s390x@12.10.0'
  - '@pnpm/exe.linux-x64-musl@12.10.0'
  - '@pnpm/exe.linux-x64@12.10.0'
  - '@pnpm/exe.win32-arm64@12.10.0'
  - '@pnpm/exe.win32-x64@12.10.0'
  - pnpm@12.10.0
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
overrides:
  'file-type@>=13.0.0 <21.3.1': '>=21.3.1'
  'brace-expansion@<1.1.13': '>=1.1.13'
  'brace-expansion@>=2.0.0 <2.0.3': '>=2.0.3'
