allowBuilds:
  esbuild: true
  sharp: true
minimumReleaseAgeExclude:
  - eslint-config-reverentgeek
  - eleventy-plugin-edgejs
  - '@11ty/eleventy@4.0.0-alpha.8'
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
overrides:
  'file-type@>=13.0.0 <21.3.1': '>=21.3.1'
  'brace-expansion@<1.1.13': '>=1.1.13'
  'brace-expansion@>=2.0.0 <2.0.3': '>=2.0.3'
